#spring:
#  datasource:
#    url: jdbc:mariadb://springboot-project-simple.cj5dbzdrxh2q.ap-northeast-2.rds.amazonaws.com:3306/personal_project
#    username: admin
#    password: ekdrms34
#    driver-class-name: org.mariadb.jdbc.Driver

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        # global 하게 적용하고 싶지 않으면 @BatchSize 를 활용할수도 있으나 global 하게 사용하는 것을 권장
        default_batch_fetch_size: 100

logging:
   level:
     # show_sql 과 달리 sql 을 logging 으로 출력
      org.hibernate.SQL: debug







